import { ClerkProvider } from "@clerk/nextjs"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import "../globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   <ClerkProvider>
     <html lang="en">
      <body className=" open-sans">{children}</body>
    </html>
   </ClerkProvider>
  )
}
